# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Multiple Challenge Management International
email: mcmi@domain.com
description: > # this means to ignore newlines until "baseurl:"
  MCMI plan, organize and implement professional development training programmes,
  meetings, seminars, study visits, conferences, and sports & leisure activities.
  MCMI provides services for diverse ranges of customers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: atMCMIasia
skype_username: MCM.International

# Build settings
markdown: kramdown
